### ISSUE TITLE
To run this example

### ISSUE THREAD

**Issue by JerryLan01** [alejandropadillav1/ArcGIS-API-Javascript-Blazor#1]
To run this example it is necessary to remove the comments from the following line in _Host.cshtml
    <script src="~/js/script.js"></script>
Other than that, this is very cool.

**Comment by alejandropadillav1** [comment]
Fixed! Uploaded!

**Comment by alejandropadillav1** [comment]
Hey @JerryLan01 Thank you, removed the comments
